#!/usr/bin/env bash

# Usage: script/parse-examples [native|wasm]

# Exit immediately if a command exits with a non-zero status.
set -e

# Parse examples in 'native' or 'wasm' mode.
mode=${1:-native}

# Change directory to project root.
cd "$(dirname "$0")/.."

example_slugs=()

# Clone a GitHub repository to the examples directory
# clone_repo OWNER NAME SHA
function clone_repo {
    repo_owner=$1
    repo_name=$2
    repo_ref=$3
    repo_slug="$repo_owner/$repo_name"
    
    example_slug="$repo_owner-$repo_name"
    example_path="examples/$example_slug"
    example_slugs+=($example_slug)
    if [ ! -d "$example_path" ]; then
        git clone "https://github.com/$repo_slug" "$example_path" --quiet
    fi
    
    pushd "$example_path" >/dev/null
    git fetch --quiet
    git reset --hard "$repo_ref" --quiet
    popd >/dev/null
}

clone_repo talonhub community 468fb16392e6a9907cb98e2526c1e5cbf3b5fc8d
clone_repo AndreasArvidsson andreas-talon e9841d0f424501df09b2f200960af2a4d65345a1
clone_repo phillco talon-axkit 9c33b80585011202eb69b2bdb9be52ed73d3ee85
clone_repo nriley talon_community f7997eeb39f5f97ae517c057f528ec56635be0d7

for example_slug in ${example_slugs[@]}; do
    script/parse-example "$example_slug" "$mode"
done
