name: CI

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  npm_config_yes: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build
      - run: npm test
      - run: npm pack
      - run: mv tree-sitter-talon-*.tgz tree-sitter-talon.tgz
      - uses: actions/upload-artifact@v3
        with:
          name: tree-sitter-talon.tgz
          path: tree-sitter-talon.tgz
          if-no-files-found: error

  build-wasm:
    name: Build WebAssembly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: mymindstorm/setup-emsdk@v12
        with:
          version: 3.1.14
          actions-cache-folder: "emsdk-cache"
      - run: npm install
      - run: npm run build
      - run: npm run build-wasm
      # Cannot test WASM due to tree-sitter/tree-sitter#1802
      # - run: npm run test-wasm
      - uses: actions/upload-artifact@v3
        with:
          name: tree-sitter-talon.wasm
          path: tree-sitter-talon.wasm
          if-no-files-found: error

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build, build-wasm]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: tree-sitter-talon.tgz
          path: build
      - uses: actions/download-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: tree-sitter-talon.wasm
          path: build
      # Apparently, I need an OTP to publish:
      # - uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/tree-sitter-talon.tgz
            build/tree-sitter-talon.wasm
